version: '2'
services:
  prometheus:
    user: root
    image: my-prometheus
    user: root
    ports:
     - 9090:9090
    container_name: prometheus

  grafana:
    user: root
    image: grafana/grafana
    ports:
     - 3000:3000
    container_name: grafana

  vault:
    user: root
    image: vault:latest
    ports:
      - 8200:8200
    container_name: vault